##################################################################
## Binary Sensors
##################################################################

# WAN Monitor
- platform: ping
  name: Ping WAN
  host: 8.8.8.8
  count: 2
  scan_interval: 60

# Kubernetes VIP Monitor
- platform: command_line
  name: Ping kube-vip
  command: '/bin/bash -c "(echo > /dev/tcp/192.168.200.10/8443) > /dev/null 2>&1 && echo ON || echo OFF"'
  scan_interval: 60
  device_class: connectivity

# OMV NAS Monitor
- platform: ping
  name: Ping OMV NAS
  host: 192.168.200.31
  count: 2
  scan_interval: 30

# Mariadb Database Monitor
- platform: ping
  name: Ping mariadb
  host: mariadb.default.svc.cluster.local
  count: 2
  scan_interval: 30

# Redis Database Monitor
- platform: ping
  name: Ping Redis
  host: redis.default.svc.cluster.local
  count: 2
  scan_interval: 30
