###################################################################################################
## Time and Date Sensors
###################################################################################################
- platform: time_date
  display_options:
  - date_time_iso
- platform: template
  sensors:
    date_formatted:
      friendly_name: "Formatted Date"
      value_template: "{{ as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%a, %b %d %Y') }}"
      icon_template: mdi:calendar-clock
    time_formatted:
      friendly_name: "Formatted Time"
      value_template: "{{ as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%I:%M %p') }}"
      icon_template: mdi:calendar-clock
