name: Check Config

on:
  workflow_dispatch:
  push:
    branches: [ '*' ]
  pull_request:

jobs:
  check_config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: university-of-york/ds-devtool-setEnvVars@v1
        with:
          envFile: dummy-secret.env
      - uses: kpucynski/action-ha-config-check@v0.1.0
        with:
          ha_version: "latest"
        env:
          HASS_EXTRA_ARGS: "-f -s -i"
